name: Tasta frontend
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Pull repository
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: oven-sh/setup-bun@v2
        name: Install bun
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run lint check
        run: bun lint:ci
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Pull repository
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: oven-sh/setup-bun@v2
        name: Install bun
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run types check
        run: bun typecheck
  expo-doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Pull repository
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: oven-sh/setup-bun@v2
        name: Install bun
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run expo-doctor
        run: bunx expo-doctor --verbose
